### ISSUE TITLE
Issue opening on Python error message

### ISSUE THREAD

**Issue by june-haya** [YuHsiangLo/SLP-AA_new#33]
Redownloaded Python and SLPAA recently. Older SLPAA files work, new one does not show SLPAA. 
(Note: デスクトップ is Desktop)
Error message on Python is as follows:

Traceback (most recent call last):
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\main.py", line 6, in <module>
    exit_code = appctxt.run()
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\app.py", line 7, in run
    self.main_window.show()
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\app.py", line 12, in main_window
    return MainWindow(self)
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\main_window.py", line 85, in __init__
    self.handle_app_settings()
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\main_window.py", line 600, in handle_app_settings
    self.app_settings['metadata']['coder'] = self.app_qsettings.value('coder', defaultValue=getuser())
  File "C:\Users\junec\AppData\Local\Programs\Python\Python39\lib\getpass.py", line 168, in getuser
    import pwd
ModuleNotFoundError: No module named 'pwd'

**Comment by YuHsiangLo** [comment]
Hi June,

This is a bug in Python itself: the pwd module is only available to users with the Unix system. For now, I changed the code so it doesn't use this module, but then the app will not be able to guess your name when you open it, so you'll need to manually change it. If you resync, the problem should be gone. But let me know if it doesn't!

**Comment by june-haya** [comment]
This worked. Thank you
