### ISSUE TITLE
more issues (with my device?)

### ISSUE THREAD

**Issue by june-haya** [YuHsiangLo/SLP-AA_new#35]
Traceback (most recent call last):
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\main.py", line 6, in <module>
    exit_code = appctxt.run()
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\app.py", line 7, in run
    self.main_window.show()
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\app.py", line 12, in main_window
    return MainWindow(self)
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\main_window.py", line 200, in __init__
    self.action_show_sub_corpus.setChecked(self.app_settings['display']['sub_corpus_show'])
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'

**Comment by YuHsiangLo** [comment]
Hi June,

I suspect that this might have something to do with the newer Python version. I've modified the code to address this issue. Could you re-sync and try again? And let me know if it works!

**Comment by june-haya** [comment]
Fixes issue! 

Note: the tabs in the window have an odd overlap. They are all still present but when first opening appears as such:

![Screenshot (5)](https://user-images.githubusercontent.com/69826712/107289843-789a3c80-6a1a-11eb-9f41-b68e2724f4db.png)

**Comment by YuHsiangLo** [comment]
Urgh that's ugly—certainly not how I imagine the interface to look. if you go to "View" on the top menu and then click "Restore default view", does the app look better now? And if you close and restart the app, it should remember the arrangement of subwindows now.

**Comment by june-haya** [comment]
Yes that fixes it. Thank you.
