### ISSUE TITLE
Issues clicking settings ->preferences

### ISSUE THREAD

**Issue by june-haya** [YuHsiangLo/SLP-AA_new#37]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\junec\AppData\Local\Programs\Python\Python39\lib\idlelib\run.py", line 155, in main
    ret = method(*args, **kwargs)
  File "C:\Users\junec\AppData\Local\Programs\Python\Python39\lib\idlelib\run.py", line 555, in runcode
    exec(code, self.locals)
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\main.py", line 6, in <module>
    exit_code = appctxt.run()
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\app.py", line 8, in run
    return self.app.exec_()
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\main_window.py", line 678, in on_action_edit_preference
    pref_dialog = PreferenceDialog(self.app_settings, parent=self)
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\preference_dialog.py", line 74, in __init__
    self.display_tab = DisplayTab(settings, parent=self)
  File "C:\Users\junec\OneDrive\デスクトップ\SLP-AA_new-main\src\main\python\gui\preference_dialog.py", line 37, in __init__
    self.show_tooltip.setChecked(settings['display']['tooltips'])
TypeError: setChecked(self, bool): argument 1 has unexpected type 'str'

**Comment by YuHsiangLo** [comment]
Okay I modified the code. Could you sync and try again?

**Comment by june-haya** [comment]
Works great!
