### ISSUE TITLE
Define locations does not pop up

### ISSUE THREAD

**Issue by june-haya** [YuHsiangLo/SLP-AA_new#9]
Working on Windows PC. On menu bar, locations, define locations produces the following error. Issue appears (on Python) as follows:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\junec\AppData\Local\Programs\Python\Python39\lib\idlelib\run.py", line 155, in main
    ret = method(*args, **kwargs)
  File "C:\Users\junec\AppData\Local\Programs\Python\Python39\lib\idlelib\run.py", line 555, in runcode
    exec(code, self.locals)
  File "C:\Users\junec\OneDrive\Documents\SLP-AA_new\src\main\python\main.py", line 6, in <module>
    exit_code = appctxt.run()
  File "C:\Users\junec\OneDrive\Documents\SLP-AA_new\src\main\python\gui\app.py", line 8, in run
    return self.app.exec_()
  File "C:\Users\junec\OneDrive\Documents\SLP-AA_new\src\main\python\gui\main_window.py", line 346, in on_action_define_location
    location_definer = LocationDefinerDialog(self.corpus.location_definition, self.app_settings, self.app_ctx, parent=self)
  File "C:\Users\junec\OneDrive\Documents\SLP-AA_new\src\main\python\gui\location_definer.py", line 470, in __init__
    self.location_tab = LocationDefinerTabWidget(location_specifications, app_settings, app_ctx, parent=self)
  File "C:\Users\junec\OneDrive\Documents\SLP-AA_new\src\main\python\gui\location_definer.py", line 429, in __init__
    self.tabbar.tabButton(3, QTabBar.LeftSide).hide()
AttributeError: 'NoneType' object has no attribute 'hide'

**Comment by YuHsiangLo** [comment]
Commit 87c9bd800bf60d79df3c0df78f432a0d15b81241 closes #9
